---
- name: Setup Apache HTTPD
  hosts: all
  become: yes

  tasks:
  - name: Ensure APT Updated
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache HTTP Installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache HTTP Installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Ensure Apache HTTP Started
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache HTTP Started
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

...

